title: Bami Log!
markdown: kramdown
url: "https://libamiew.github.io/"
baseurl: "/bamilog"

# for atom feed
author:
  name: Bami Li
  email: libamiew@gmail.com
  image: "https://avatars.githubusercontent.com/u/75570052?v=4"
  bio: 3ë…„ì°¨ ìœ ë‹ˆí‹° ê°œë°œì <b> ì´ì£¼ì—° </b> ì…ë‹ˆë‹¤. <br>
       ì´ê²ƒì €ê²ƒ ê¸°ìˆ ì„ ë°°ì›Œë‚˜ê°€ëŠ” ê³¼ì •ì„ ë‹´ì•˜ìŠµë‹ˆë‹¤. <br><br>
       ì¬ë°Œê²Œ ë´ì£¼ì„¸ìš” ğŸ‘©â€
  github: "libamiew"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/
